using System;
using System.Collections.Generic;
using UnityEngine;

namespace EscapeOffice
{
    // Everything the game loads from the Other Side asset pack at runtime, by name.
    // Generated by Tools → Other Side → Build Assets into Assets/Resources/ArtCatalog.asset;
    // don't edit it by hand.
    public class ArtCatalog : ScriptableObject
    {
        [Serializable]
        public struct ThemeDecor
        {
            public string theme;
            public List<string> prefabs;
        }

        public List<GameObject> prefabs = new List<GameObject>();
        public List<Material> materials = new List<Material>();
        public List<Sprite> sprites = new List<Sprite>();
        public List<AudioClip> clips = new List<AudioClip>();
        public List<ThemeDecor> decor = new List<ThemeDecor>();
        public Font codeFont;

        Dictionary<string, GameObject> prefabIndex;
        Dictionary<string, Material> materialIndex;
        Dictionary<string, Sprite> spriteIndex;
        Dictionary<string, AudioClip> clipIndex;

        public GameObject Prefab(string name) => Find(ref prefabIndex, prefabs, name);
        public Material Material(string name) => Find(ref materialIndex, materials, name);
        public Sprite Sprite(string name) => Find(ref spriteIndex, sprites, name);
        public AudioClip Clip(string name) => Find(ref clipIndex, clips, name);

        public List<string> DecorFor(string theme)
        {
            foreach (var d in decor)
                if (d.theme == theme) return d.prefabs;
            return null;
        }

        static T Find<T>(ref Dictionary<string, T> index, List<T> items, string name) where T : UnityEngine.Object
        {
            if (index == null)
            {
                index = new Dictionary<string, T>(StringComparer.OrdinalIgnoreCase);
                foreach (var i in items)
                    if (i != null) index[i.name] = i;
            }
            return name != null && index.TryGetValue(name, out var found) ? found : null;
        }
    }
}
